apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workerd
  labels:
    app: {{ .Release.Name }}-workerd
spec:
  replicas: {{ .Values.workerd.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-workerd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-workerd
    spec:
      containers:
        - name: workerd
          image: "{{ .Values.workerd.image.repository }}:{{ .Values.workerd.image.tag }}"
          ports:
            - containerPort: {{ .Values.workerd.service.port }}
          command:
            - /usr/bin/workerd
          args:
            - "--verbose"
            - "serve"
            - "/app/config.capnp"
          imagePullPolicy: {{ .Values.workerd.image.pullPolicy }}
          volumeMounts:
            - name: workerd-config
              mountPath: /app/config.capnp
              subPath: config.capnp
            - name: worker-script
              mountPath: /app/scripts/worker.js
              subPath: worker.js
      volumes:
        - name: workerd-config
          configMap:
            name: {{ .Release.Name }}-workerd-config
        - name: worker-script
          configMap:
            name: {{ .Release.Name }}-workerd-script
            items:
              - key: worker.js
                path: worker.js
