package:
  name: workerd
  version: 1.20241214.0
  epoch: 0
  description: The JavaScript / Wasm runtime that powers Cloudflare Workers
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - glibc-dev
  target-architecture:
    - aarch64
    - x86_64

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - busybox
      - ca-certificates
      - wget
      - wolfi-base

pipeline:
  - name: get
    runs: |
      if [ "${{build.arch}}" = "x86_64" ]; then
        wget -O workerd.gz https://github.com/cloudflare/workerd/releases/download/v${{package.version}}/workerd-linux-64.gz
      elif [ "${{build.arch}}" = "aarch64" ]; then
        wget -O workerd.gz https://github.com/cloudflare/workerd/releases/download/v${{package.version}}/workerd-linux-arm64.gz
      fi

  - name: install
    runs: |
      gunzip -c workerd.gz > workerd
      install -Dm755 workerd ${{targets.destdir}}/usr/bin/workerd

  - uses: strip
